# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8471626cbabc71e2a495347b7b8f8f9ae453cdc35ccc6ce9d5e1ae1cb4f1552a61d12077e1e1118475e498d1b40ea3492eab08324395990c0f08b5c2a1a224ab

test:
  secret_key_base: 380edafc9b0cb190aa8c68c766b1262cebc17664b6bb5f61ce1f7b289d7761b4ded75a40d3bca8c0a53d98489dcbd0e3b4bc818cbd170348a232dfe24c126b4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
